[tool.poetry]
name = "openchatui"
version = "0.1.0"
description = ""
authors = ["laxitshahi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.35.0"
proxyllm = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
